In [6]:
print("fit a model with", 11, "variables")
print?

fit a model with 11 variables


Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method

# About numpy

In [3]:
import numpy as np
x = np.array([3, 4, 5])
y = np.array([4, 9, 7])
x + y

array([ 7, 13, 12])

In [4]:
x = np.array([[1, 2], 
              [3, 4]])
x


array([[1, 2],
       [3, 4]])

In [6]:
x.ndim

2

In [7]:
x.dtype

dtype('int64')

In [9]:
np.array([[1, 2], [3.0, 4]]).dtype

dtype('float64')

In [10]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if ``__array__`` returns a copy, if obj is a nested
    sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly crea

In [11]:
x.shape

(2, 2)

In [12]:
x.sum()

10

In [13]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [16]:
x = np.array([1, 2, 3, 4, 5, 6])
print("Beginning x: \n", x)
x_reshape = x.reshape((2, 3))
print("reshaped x: \n", x_reshape)

Beginning x: 
 [1 2 3 4 5 6]
reshaped x: 
 [[1 2 3]
 [4 5 6]]


In [17]:
x_reshape[0, 0]

1

In [18]:
x_reshape[1, 2]

6

In [19]:
print("x before we modify x_reshape: \n", x)
print("x_reshape before we modify x_reshape: \n", x_reshape)
x_reshape[0, 0] = 100
print("x_reshape after we modify its top left element: \n", x_reshape)
print("x after we modify top left element of x_reshape: \n", x)

x before we modify x_reshape: 
 [1 2 3 4 5 6]
x_reshape before we modify x_reshape: 
 [[1 2 3]
 [4 5 6]]
x_reshape after we modify its top left element: 
 [[100   2   3]
 [  4   5   6]]
x after we modify top left element of x_reshape: 
 [100   2   3   4   5   6]


modifying x_reshape also modified x because the two objects occupy the same space in memory.

In [21]:
x_reshape.shape, x_reshape.ndim, x_reshape.T # T provides the transpose

((2, 3),
 2,
 array([[100,   4],
        [  2,   5],
        [  3,   6]]))

In [22]:
np.sqrt(x)

array([10.        ,  1.41421356,  1.73205081,  2.        ,  2.23606798,
        2.44948974])

In [23]:
x ** 2

array([10000,     4,     9,    16,    25,    36])

In [25]:
x ** 0.5

array([10.        ,  1.41421356,  1.73205081,  2.        ,  2.23606798,
        2.44948974])

# Generating random data

In [26]:
np.random.normal()

-1.8399607586321665

In [28]:
x = np.random.normal(size = 50)
x

array([-0.17518802,  0.26797438, -1.16299319, -1.01367673,  0.14269884,
       -0.57742633,  0.31072307, -0.5030522 ,  0.43455181,  0.05998284,
       -0.25110248,  0.39099868,  0.7135321 , -0.27668586, -1.3179115 ,
       -1.83140901, -0.58143199,  0.73627076,  1.09589104,  0.87796765,
        0.66238186,  0.15128843,  0.51230297, -0.97455129, -0.36574088,
       -0.79523512, -0.05917481, -0.71901822, -1.33666957,  0.75662007,
        0.33589368,  0.47337383,  1.2330748 ,  0.3548226 , -0.37502082,
       -1.06700309,  0.46264116,  0.31193081,  0.5310339 ,  0.80525301,
        2.39919742, -0.23276805,  1.8442754 , -1.47042489,  2.87366537,
       -0.97609198,  0.64654383, -0.48690713, -0.05200996, -0.32550725])

In [29]:
y = x + np.random.normal(loc = 50, scale = 1, size = 50)

In [30]:
np.corrcoef(x, y)

array([[1.       , 0.7115519],
       [0.7115519, 1.       ]])

In [31]:
print(np.random.normal(scale = 5, size = 2))
print(np.random.normal(scale = 5, size = 2))

[-0.17310339 -5.38119666]
[-1.62479413 -7.26955526]


use np.random.default_rng to get a random number generator with fixed sequence of random numbers

In [32]:
rng = np.random.default_rng(1303)
print(rng.normal(scale = 5, size = 2))
rng2 = np.random.default_rng(1303)
print(rng2.normal(scale = 5, size = 2))

[ 4.09482632 -1.07485605]
[ 4.09482632 -1.07485605]
